//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Rating = new HashSet<Rating>();
            this.Rating1 = new HashSet<Rating>();
            this.Relatie = new HashSet<Relatie>();
            this.Relatie1 = new HashSet<Relatie>();
            this.Aptitudini = new HashSet<Aptitudini>();
            this.Mesaj_Client_Client = new HashSet<Mesaj_Client_Client>();
            this.Mesaj_Client_Client1 = new HashSet<Mesaj_Client_Client>();
            this.Mesaj_Client_Companie = new HashSet<Mesaj_Client_Companie>();
            this.Mesaj_Companie_Client = new HashSet<Mesaj_Companie_Client>();
        }
    
        public int ID_Client { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<System.DateTime> Data_Nasterii { get; set; }
        public string Email { get; set; }
        public byte[] Poza { get; set; }
        public string Facultate_absolvita { get; set; }
        public int ID_sex { get; set; }
        public int ID_statut_social { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Nationalitate { get; set; }
        public string Limbi_straine { get; set; }
        public string Username { get; set; }
        public string Parola { get; set; }
    
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual ICollection<Rating> Rating1 { get; set; }
        public virtual ICollection<Relatie> Relatie { get; set; }
        public virtual ICollection<Relatie> Relatie1 { get; set; }
        public virtual ICollection<Aptitudini> Aptitudini { get; set; }
        public virtual ICollection<Mesaj_Client_Client> Mesaj_Client_Client { get; set; }
        public virtual ICollection<Mesaj_Client_Client> Mesaj_Client_Client1 { get; set; }
        public virtual ICollection<Mesaj_Client_Companie> Mesaj_Client_Companie { get; set; }
        public virtual ICollection<Mesaj_Companie_Client> Mesaj_Companie_Client { get; set; }
    }
}
