//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companie
    {
        public Companie()
        {
            this.Mesaj_Companie_Client = new HashSet<Mesaj_Companie_Client>();
            this.Aptitudini = new HashSet<Aptitudini>();
        }
    
        public int ID_Companie { get; set; }
        public string Director_companie { get; set; }
        public string Nume_companie { get; set; }
        public string Adresa_companie { get; set; }
        public string Email_companie { get; set; }
        public string Telefon_companie { get; set; }
        public string UsernameC { get; set; }
        public string ParolaC { get; set; }
    
        public virtual ICollection<Mesaj_Companie_Client> Mesaj_Companie_Client { get; set; }
        public virtual ICollection<Aptitudini> Aptitudini { get; set; }
    }
}
