//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LinkedinEntities5 : DbContext
    {
        public LinkedinEntities5()
            : base("name=LinkedinEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aptitudini> Aptitudini { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Companie> Companie { get; set; }
        public virtual DbSet<Mesaj_Client_Client> Mesaj_Client_Client { get; set; }
        public virtual DbSet<Mesaj_Client_Companie> Mesaj_Client_Companie { get; set; }
        public virtual DbSet<Mesaj_Companie_Client> Mesaj_Companie_Client { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Relatie> Relatie { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Statut_social> Statut_social { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<CautaClient_Result> CautaClient(string nume, string prenume)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CautaClient_Result>("CautaClient", numeParameter, prenumeParameter);
        }
    
        public virtual ObjectResult<CautaCompanie_Result> CautaCompanie(string nume)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CautaCompanie_Result>("CautaCompanie", numeParameter);
        }
    
        public virtual ObjectResult<Procedura_Result> Procedura(string nume)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedura_Result>("Procedura", numeParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> AfiseazaMesaje(string id_client_logat)
        {
            var id_client_logatParameter = id_client_logat != null ?
                new ObjectParameter("id_client_logat", id_client_logat) :
                new ObjectParameter("id_client_logat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AfiseazaMesaje", id_client_logatParameter);
        }
    
        public virtual ObjectResult<string> AfiseazaMesajePentruClient(string id_client_logat)
        {
            var id_client_logatParameter = id_client_logat != null ?
                new ObjectParameter("id_client_logat", id_client_logat) :
                new ObjectParameter("id_client_logat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AfiseazaMesajePentruClient", id_client_logatParameter);
        }
    
        public virtual ObjectResult<MesajePentruClient_Result> MesajePentruClient(string id_client_logat)
        {
            var id_client_logatParameter = id_client_logat != null ?
                new ObjectParameter("id_client_logat", id_client_logat) :
                new ObjectParameter("id_client_logat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MesajePentruClient_Result>("MesajePentruClient", id_client_logatParameter);
        }
    
        public virtual ObjectResult<AfiseazaMesajePentruClient1_Result> AfiseazaMesajePentruClient1(Nullable<int> id_client_logat)
        {
            var id_client_logatParameter = id_client_logat.HasValue ?
                new ObjectParameter("id_client_logat", id_client_logat) :
                new ObjectParameter("id_client_logat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfiseazaMesajePentruClient1_Result>("AfiseazaMesajePentruClient1", id_client_logatParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AfiseazaNotificari(Nullable<int> id_client_logat)
        {
            var id_client_logatParameter = id_client_logat.HasValue ?
                new ObjectParameter("id_client_logat", id_client_logat) :
                new ObjectParameter("id_client_logat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AfiseazaNotificari", id_client_logatParameter);
        }
    
        public virtual ObjectResult<ClientDupaID_Result> ClientDupaID(Nullable<int> id_client)
        {
            var id_clientParameter = id_client.HasValue ?
                new ObjectParameter("id_client", id_client) :
                new ObjectParameter("id_client", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientDupaID_Result>("ClientDupaID", id_clientParameter);
        }
    
        public virtual ObjectResult<string> UserDupaID(Nullable<int> id_client)
        {
            var id_clientParameter = id_client.HasValue ?
                new ObjectParameter("id_client", id_client) :
                new ObjectParameter("id_client", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UserDupaID", id_clientParameter);
        }
    
        public virtual ObjectResult<string> UserDupaIDforC(Nullable<int> id_comp)
        {
            var id_compParameter = id_comp.HasValue ?
                new ObjectParameter("id_comp", id_comp) :
                new ObjectParameter("id_comp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UserDupaIDforC", id_compParameter);
        }
    }
}
