//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj_Companie_Client
    {
        public int ID_companie { get; set; }
        public int ID_client { get; set; }
        public int ID_mesaj { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Companie Companie { get; set; }
        public virtual Mesaje Mesaje { get; set; }
    }
}
