//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj_Client_Companie
    {
        public int ID { get; set; }
        public int ID_Client_send { get; set; }
        public int ID_Companie_receive { get; set; }
        public string Mesaj { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Companie Companie { get; set; }
    }
}
