//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID_client_send { get; set; }
        public int ID_client_receive { get; set; }
        public int Nota { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
